app:
    image: rppf/laracker:latest
    working_dir: /var/www
    volumes:
        - ./:/var/www
    links:
        - db
    environment:
        DB_HOST: db
        DB_DATABASE: dbname
        DB_USERNAME: root
        DB_PASSWORD: p455w0rd
        DB_CONNECTION: mysql

db:
    image: mariadb
    environment:
        MYSQL_DATABASE: dbname
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: p455w0rd

webserver:
    image: nginx:1.10-alpine
    volumes:
        - ./vhost.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
        - app
    ports:
        - 8080:80
