version: '2'

services:
  web:
    image: rppf/laravel-web
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
      - "443:443"
      - "9000:9000"
    links:
      - app
    depends_on:
      - app

  app:
    image: rppf/laravel-app
    volumes:
      - ./:/var/www
    links:
      - database
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  database:
    image: mysql:5.7.18
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=homestead"
    ports:
      - "33061:3306"
